<?php

/**
 * @file
 * Module hide shipping address pane from checkout.
 */

/******************************************************************************
 * Drupal Hooks                                                               *
 ******************************************************************************/

/**
 * Implements hook_checkout_pane_alter().
 */
function uc_hide_ship_address_checkout_pane_alter(&$panes) {
  foreach ($panes as &$pane) {
    if ($pane['id'] == 'simple_quote') {
      // get and check uc_hide_ship_address variable
      $uc_hide_ship_address = variable_get('uc_hide_ship_address', array());
      if (empty($uc_hide_ship_address)) {
        return;
      }

      // generate js array with methods id's than have hide option
      $js_id_array = '';
      foreach ($uc_hide_ship_address as $key => $method_id) {
        $js_id_array .= "hide_id.push('" . $method_id . "---0');";
      }

      $js = "
        $(function() {
          $('#simple_quote-pane input:radio').click(function() {
            var hide_id = new Array();" . $js_id_array . "
            var pane = $('#delivery-pane');
            if (jQuery.inArray($(this).attr('value'), hide_id) == -1) {
              pane.show('fast');
            } else {
              pane.hide('fast');
            }
          }).filter(':checked').click();
        });";
      // add js for hiding delivery pane
      drupal_add_js($js, 'inline');
    }
  }
}

/**
 * Implements hook_form_uc_quote_method_settings_alter().
 */
function uc_hide_ship_address_form_uc_quote_method_settings_alter(&$form, &$form_state) {
  // add checkbox to admin page
  $methods = uc_quote_shipping_method_options();
  $uc_hide_ship_address = variable_get('uc_hide_ship_address', array());

  if (is_array($methods)) {
    foreach ($methods as $id => $title) {
      $form['methods'][$id]['uc_hide_ship_address'] = array(
        '#type' => 'checkbox',
        '#default_value' => in_array($id, $uc_hide_ship_address),
      );
    }
  }
  // add submit handler
  $form['#submit'][] = 'uc_hide_ship_address_method_settings_submit';
}

/**
 * Implements hook_form_uc_cart_checkout_form_alter().
 */
function uc_hide_ship_address_form_uc_cart_checkout_form_alter(&$form, &$form_state) {
  $form['#after_build'][] = 'uc_hide_ship_address_checkout_form_after_build';
}

/**
 * Implements hook_theme_registry_alter().
 */
function uc_hide_ship_address_theme_registry_alter(&$theme_registry) {
  if (!empty($theme_registry['uc_quote_method_settings'])) {
    $theme_registry['uc_quote_method_settings']['function'] = 'uc_hide_ship_address_theme_uc_quote_method_settings';
  }
}

/******************************************************************************
 * Module Functions                                                           *
 ******************************************************************************/

/**
 * Displays a formatted list of shipping quote methods and form elements
 * with hide delivery pane option. Overrides theme_uc_quote_method_settings().
 *
 * @see uc_quote_method_settings()
 * @ingroup themeable
 */
function uc_hide_ship_address_theme_uc_quote_method_settings($form) {
  drupal_add_tabledrag('uc-quote-methods', 'order', 'sibling', 'uc-quote-method-weight');

  $header = array(t('Shipping method'), t('List position'), t('Hide delivery pane'));
  $rows = array();
  foreach (element_children($form['methods']) as $method) {
    $row = array(
      drupal_render($form['methods'][$method]['uc_quote_enabled']),
      drupal_render($form['methods'][$method]['uc_quote_method_weight']),
      drupal_render($form['methods'][$method]['uc_hide_ship_address']),
    );

    $rows[] = array(
      'data' => $row,
      'class' => 'draggable',
    );
  }
  $output = theme('table', $header, $rows, array('id' => 'uc-quote-methods'));

  $output .= drupal_render($form);
  return $output;
}

/**
 * Additional form submission handler for uc_quote_method_settings().
 *
 * @see uc_quote_method_settings()
 * @see uc_quote_method_settings_validate()
 */
function uc_hide_ship_address_method_settings_submit($form, &$form_state) {
  // save uc_hide_ship_address flag value
  $uc_hide_ship_address = array();
  foreach ($form_state['values']['methods'] as $id => $method) {
    if ($method['uc_hide_ship_address']) {
      $uc_hide_ship_address[] = $id;
    }
  }

  variable_set('uc_hide_ship_address', $uc_hide_ship_address);
}

/**
 * Callback for uc_cart_checkout_form on after_build.
 *
 */
function uc_hide_ship_address_checkout_form_after_build($form, &$form_state) {
  // get uc_hide_ship_address variable
  $uc_hide_ship_address = variable_get('uc_hide_ship_address', array());
  if (empty($uc_hide_ship_address)) {
    return $form;
  }
  // get method id from radio button value
  // uc_simple_quote added '---$id' for each method variant, we dont care about it
  $selected_option = substr($form['panes']['simple_quote']['quote-option']['#value'], 0, -4);;
  // if user selected method with hide checked
  if (in_array($selected_option, $uc_hide_ship_address)) {
    // set required propery to false
    $required = variable_get('uc_address_fields_required', drupal_map_assoc(array(
      'first_name',
      'last_name',
      'street1',
      'city',
      'zone',
      'postal_code',
      'country',
    )));
    foreach ($required as $key => $field) {
      $form['panes']['delivery']['delivery_' . $field]['#required'] = FALSE;
    }
  }

  return $form;
}
